package support;

public class trafimukXpathLib {
    public static String url = "http://ask-stage.portnov.com";
    public static String emailField = "//input[@formcontrolname='email']";
    public static String passwordField = "//input[@formcontrolname='password']";
    public static String signInButton = "//button[@type='submit']";
    public static String menuQuizzes = "//h5[contains(text(),'Quizzes')]";
    public static String newQuizButton = "//span[contains(text(),'Create New Quiz')]";
    public static String quizTitle = "//input[@formcontrolname='name']";
    public static String addQbutton ="//mat-icon[contains(text(),'add_circle')]";
    public static String qTypeMC ="//*[contains(text(),'Q1')]/../../..//*[contains(text(),'Multiple')]";
    public static String questionField ="//*[contains(text(),'Q1')]/../../..//*[@placeholder='Question *']";
    public static String option1Field ="//*[contains(text(),'Q1')]/../../..//*[@placeholder='Option 1*']";
    public static String option2Field ="//*[contains(text(),'Q1')]/../../..//*[@placeholder='Option 2*']";
    public static String checkbox1 = "(//*[contains(text(),'Q1')]/../../..//mat-checkbox)[1]";
    public static String saveButton = "//span[contains(text(),'Save')]";
    public static String email = "iseebugsandbugs@gmail.com";
    public static String psw = "Testing#1";
    public static String quizTitleTxt = "GJ Quiz 1";
    public static String questionFieldTxt = "A&1";
    public static String questionFieldTxt1 = "a";
    public static String questionFieldTxt100 = "A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring w&1";
    public static String questionFieldTxt1000 = "A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single stroke at the present moment; and yet I feel that I never was a greater artist than now. When, while the lovely valley teems with vapour around me, and the meridian sun strikes the upper surface of the impenetrable foliage of my trees, and but a few stray gleams steal into the inner sanctuary, I throw myself down among the tall grass by the trickling stream; and, as I lie close to the earth, a thousand unknown plants are noticed by me: when I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects and flies, then I feel&1";
    public static String questionFieldTxt1001 = "A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single stroke at the present moment; and yet I feel that I never was a greater artist than now. When, while the lovely valley teems with vapour around me, and the meridian sun strikes the upper surface of the impenetrable foliage of my trees, and but a few stray gleams steal into the inner sanctuary, I throw myself down among the tall grass by the trickling stream; and, as I lie close to the earth, a thousand unknown plants are noticed by me: when I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects and flies, then I feel &1";
    public static String option1FieldTxt = "A";
    public static String option2FieldTxt = "A&1";
    public static String roleLbl = "//div[@class='info']//p";
    public static String listOfQuizzes = "//h4[contains(text(),'List of Quizzes')]";
    public static String q1Card = "//mat-panel-title[contains(text(),'Q1: new empty question')]";
    public static String errAtLeastOneCorrectAns = "//div[contains(text(),'*Choose at least one correct answer')]";
    public static String errReqFieldQ = "(//*[contains(text(),'Q1')]/../../..//*[contains(text(),'This field')])[1]";
    public static String errReqFieldOpt1 = "(//*[contains(text(),'Q1')]/../../..//*[contains(text(),'This field')])[2]";
    public static String errReqFieldOpt2 = "(//*[contains(text(),'Q1')]/../../..//*[contains(text(),'This field')])[3]";
    public static String errQuizNotCompleted = "//simple-snack-bar[contains(text(),'not completed')]";
    public static String errAuthFailed = "//simple-snack-bar[contains(text(),'failed')]";
    public static String errInvalidEmail = "//*[contains(text(),'valid email')]";
    public static String errReqPsw = "//*[contains(text(),'field is required')]";
    public static String errLength = "";
}
